### PR TITLE
Api Integration and Pop Up Modal for Find Us Page

### PR DESCRIPTION
**Pull request by Ewabunmi**
Api Integration and Pop Up Modal for Find Us Page

### CODE REVIEW

**Review by krepinnegga — APPROVED** [review]

**Comment by krepinnegga** [comment]
@Ewabunmi  Can you please submit the form and show a picture of the modal pop up so i can merge?

**Review by oddoye — APPROVED** [review]
Looks good to me

**Comment by Ewabunmi** [comment]
Screenshot 202333333333333333333

**Comment by Ewabunmi** [comment]
> @Ewabunmi Can you please submit the form and show a picture of the modal pop up so i can merge?

I have

**Pull request merged**
