### PR TITLE
Added new blog 'Green Technology"

### PR DESCRIPTION
**Pull request by Nelson877**
Green

### CODE REVIEW

**Review by krepinnegga — APPROVED** [review]

**Comment by oddoye** [comment]
@Nelson877 this will bring a merge conflict after one of our prs is merged, so @krepinnegga can you merge it so i can resolve it ?

**Comment by krepinnegga** [comment]
> @Nelson877 this will bring a merge conflict after one of our prs is merged, so @krepinnegga can you merge it so i can resolve it ?

You guys worked on the same page?

**Comment by oddoye** [comment]
> > @Nelson877 this will bring a merge conflict after one of our prs is merged, so @krepinnegga can you merge it so i can resolve it ?
> 
> @oddoye @Nelson877 You guys worked on the same page?

Yeah, we linked our blogs to the same page so the positioning of the articles will conflict.

**Comment by krepinnegga** [comment]
> > > @Nelson877 this will bring a merge conflict after one of our prs is merged, so @krepinnegga can you merge it so i can resolve it ?
> > 
> > 
> > @oddoye @Nelson877 You guys worked on the same page?
> 
> Yeah, we linked our blogs to the same page so the positioning of the articles will conflict. @krepinnegga i say we merge both PRs now so we resolve it now. I think you should merge mine first

@oddoye okay do you have 2 approvals on your pr?

**Comment by krepinnegga** [comment]
> > > > @Nelson877 this will bring a merge conflict after one of our prs is merged, so @krepinnegga can you merge it so i can resolve it ?
> > > 
> > > 
> > > @oddoye @Nelson877 You guys worked on the same page?
> > 
> > 
> > Yeah, we linked our blogs to the same page so the positioning of the articles will conflict. @krepinnegga i say we merge both PRs now so we resolve it now. I think you should merge mine first
> 
> @oddoye Merged i am waiting for the 2nd approval on @Nelson877 PR.

@Nelson877  We would have to hop on a call and resolve the merge conflict let me know when you are available

**Review by oddoye — APPROVED** [review]

**Review by Ewabunmi — APPROVED** [review]
Great

**Pull request merged**
